branches:
  only:
  - dev

install:
  # Change to a home directory
  - cd $HOME
  - wget https://www.openssl.org/source/openssl-1.1.0b.tar.gz
  - tar xzf openssl-1.1.0b.tar.gz
  - cd openssl-1.1.0b
  - ./Configure linux-x86_64 shared no-ssl2 no-ssl3 no-comp enable-ec_nistp_64_gcc_128 -Wl,-rpath,/usr/local/lib
  - make -s -j 4
  - sudo make -s install
  - /usr/local/bin/openssl version
  - ldd /usr/local/bin/openssl
  - export CFLAGS="-I/usr/local/include/ -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lssl -lcrypto"
  - export CXXFLAGS="-I/usr/local/include/ -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lssl -lcrypto"
  - wget https://curl.haxx.se/download/curl-7.51.0.tar.gz
  - tar xzf curl-7.51.0.tar.gz
  - cd curl-7.51.0
  - ./configure --with-ssl=/usr/local
  - make -s -j 4
  - sudo make -s install
  - which curl
  - ldd /usr/local/bin/curl
  - /usr/local/bin/curl -V
  - curl -V
  - openssl version -v
  - sudo apt-get install -y --force-yes software-properties-common
  - sudo apt-get install python-software-properties
  # PPA for PHP 7.0 and extensions
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo add-apt-repository -y ppa:ondrej/php-qa
  # Update apt-get
  - sudo apt-get update
  # Install latest curl PHP extension for lara-block-io
  - sudo apt-get install -y --force-yes php7.0 php7.0-common php-pear php7.0-gmp php7.0-mcrypt php7.0-bcmath php7.0-curl php7.0-cli php7.0-fpm php7.0-gd php7.0-json php7.0-mysql php7.0-readline php7.0-xdebug php7.0-intl php7.0-imap php7.0-mbstring php7.0-ldap php7.0-ps php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-pdo php7.0-tokenizer php7.0-xml
  # Check curl version
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - sudo mv composer.phar /usr/local/bin/composer
  # updates composer on travis
  - travis_retry composer self-update
  # clear composer cache, might speed up finding new tags
  - travis_retry composer clear-cache
  # create a new laravel project in the subfolder laravel-sandbox
  - composer create-project laravel/laravel laravel-sandbox 5.4.*
  # change to laravel root
  - cd laravel-sandbox
  # Make a packages directory
  - mkdir packages
  # Make our vendor directory
  - cd packages
  - mkdir blockavel
  #  Copy our project here
  - sudo mv $TRAVIS_BUILD_DIR $HOME/laravel-sandbox/packages/blockavel/lara-block-io
  # Change to package directory
  - cd blockavel/lara-block-io
  # Install dependencies
  - composer install
  # Expose LaraBlockIo to Laravel
  - sudo cp ./tests/config/app.php $HOME/laravel-sandbox/config/app.php
  # Copy the config file
  - cp src/config/main.php $HOME/laravel-sandbox/config/larablockio.php

script: vendor/bin/phpunit

after_failure:
  - cat /var/log/travis-queue.log
